version: '3'

services:

  postgres:
    image: 'postgres:15.1-alpine'
    ports:
      - "5438:5432"
    env_file:
      - .env
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    networks:
      - test_network
    volumes:
      - db-data1:/var/lib/postgresql/data1

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    networks:
      - test_network
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_CLIENT_PORT}
      - ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME}
    ports:
      - '2181:2181'
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    networks:
       - test_network
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    ports:
      - '29092:29092'
    volumes:
      - kafka-data:/var/lib/kafka/data

  debezium:
    image: debezium/connect:2.4.0.Final
    networks:
      - test_network
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=2
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
      - VALUE_CONVERTER_SCHEMAS_ENABLE=false
    user: root
    #    command:
    #      - bash
    #      - -c
    #      - "cd /on-startup; ls; ./run.sh"
    volumes:
      - debezium-data:/debezium/data
      - ./conf/:/on-startup/

  dwh-clickhouse:
    image: clickhouse/clickhouse-server:23.9.1.1854-alpine
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
    environment:
      - TIMEZONE=Europe/Kyiv
    networks:
      - test_network

networks:
  test_network:

volumes:
  db-data1:
    driver: local
  debezium-data:
    driver: local
  kafka-data:
    driver: local
  zookeeper-data:
    driver: local