server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka
spring:
  application:
    name: driver-service
  kafka:
    bootstrap-servers: localhost:29092
