spring:
  kafka:
    bootstrap-servers: localhost:29092
  application:
    name: logist-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka
