server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: dwh-service
  kafka:
    bootstrap-servers: localhost:29092

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
