version: '3'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: qwe123
    volumes:
      - ./keycloak/realms/autobahn_v1.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
      - --features admin-fine-grained-authz

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - '15672:15672'
      - '5672:5672'

  postgres:
    container_name: gnivc_db
    image: 'postgres:15.1-alpine'
    ports:
      - "5436:5432"
    env_file:
      - .env
    networks:
      - test_network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  test_network:

volumes:
  minio:
  db-data:
    driver: local
